# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 01:08
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.CharField(default=0, max_length=10, verbose_name='数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='count',
            field=models.CharField(default=0, max_length=10, verbose_name='数量'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文'),
        ),
    ]
